config/routes.rb
Atportugal::Application.routes.draw do
  root :to => "home#index"
  
  
  match 'restaurants/advanced_search' => "restaurants#advanced_search"
  match '/restaurants/search/:district' => "restaurants#search"
  
  match '/users/save_rest_prefs' => "users#save_rest_prefs"
  match '/users/setpass' => "users#setpass"
  match '/users/resetpassword' => "users#resetpassword"
  match 'users/sendpassemail' => "users#sendpassemail"
  match 'users/resetpass' => "users#resetpass"
  match 'users/changepass' => "users#changepass"
  match 'users/editprofile' => "users#editprofile"
  match 'users/saveprofile' => "users#saveprofile"
  match 'users/updateaccount' => "users#updateaccount"
  match 'users/myprofile' => "users#myprofile"
  match 'users/contents' => "users#contents"
  match 'search/simplesearch' => "search#simplesearch"
  match 'search/advancedsearch' => "search#advancedsearch"
  
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  resource :users
  #resources :users
  resource :session
  resource :home
  resource :search
  resources :restaurant_ratings
  resources :restaurant_comments
  resources :restaurants
end

app/controllers/users_controller.rb
require 'digest'
require 'time'
require 'date'
class UsersController < ApplicationController
  def new
    @user = User.new
    
  end

  def create
    user = User.new(params[:user])
    profile = Profile.new
    



    user_pre_preference = UserPrePreference.new
    
    user.profile = profile
    if user.save
      user_pre_preference.user_id = profile.user_id
      
      rest_categories = RestaurantCategory.all
      rest_categories.each { |cat|  
        pre_pref = UserPrePreferencesOfRestaurantCategory.new
        pre_pref.restaurant_category_id = cat.id
        pre_pref.user_pre_preference_id = user_pre_preference.id
        pre_pref.significance = 0
        user_pre_preference.user_pre_preferences_of_restaurant_categories << pre_pref
       }
        #cena para inicializar clicks das categorias de restaurantes
        rest_cats = RestaurantCategory.all
        rest_cats.each { |cat|

          cat_click = RestaurantCategoriesClick.new
          cat_click.user_id = user.id
          cat_click.restaurant_category_id = cat.id
          cat_click.number_of_clicks = 0
          cat_click.save
        }
    
      
      user_pre_preference.save

      respond_to do |format|
        format.html { redirect_to root_path, :notice=>'Utilizador criado com sucesso!!!' }
        format.js
      end
      
      
    else
      render :action =>'new'
    end
  end

  def edit
    @user = current_user

  end

  def updateaccount

    @user = current_user
    if(params[:user][:password] != nil && params[:user][:password] != "" && params[:user][:password] == params[:user][:password_confirmation])
      #logger.debug "okokokokokopass:" << params[:user][:password]
      if @user.update_attributes(params[:user])
        render :action => 'myprofile', :notice =>'Dados do utilizador atualizados com sucesso!'
      else
        if(request.referer == "/users/editprofile")
          render :action => 'editprofile'
        else
          render :action => 'edit'
        end
      end
    else
      params[:user].delete(:password)
      if(@user.update_attributes(params[:user]))
        render :action => 'myprofile', :notice =>'Dados do utilizador atualizados com sucesso!'
      else
        render :action => 'editprofile'
      end

    end
    
  end
  #this is just to run the JS associated
  def setpass
   
    
  end
  #Here we verify if user email submit exist in the database and procede with respective actions
  def sendpassemail
    @user = User.find_by_email(params[:email])

    #if the user exist, we create a new PasswordResetRequest record and send an email to the respective user if he doesn't exist we just process a JS to
    # show a error message.
    if(@user!=nil)
      
      o = PasswordResetRequest.new :user_email =>@user.email
      o.save;
      pass_rest = PasswordResetRequest.where(:user_email=>@user.email).order("created_at DESC").limit(1)
      a = pass_rest[0].id.to_s()
      a << @user.email
      hash = Digest::SHA1.hexdigest(a)

      #logger.debug "FDDDDDDDDDDXXXXXXXXXXXXXx"<< @a.inspect
      p = PasswordResetRequest.find(pass_rest[0].id)
      p.request_hash = hash
      p.save
      #@pass_rest.update_attributes :request_hash=>@hash
      Notifier.send_pass_reset(@user).deliver
    else
      render 'nonexist.js.erb'
    end
  end
  
  #This is just to verify if the user is valid, and the request for pass canche is up to date this comes from the link sent to user email
  def resetpass
    dif = nil
    @user = nil
    @valid_reset = false

    hash_request = params['key']
    p = PasswordResetRequest.find_by_request_hash(hash_request)
    #Get the hours that passed from the request time if this value is supirior to 12 hours we shoul'd let the user reset the pass   
    if(p != nil)
      dif = (Time.now - p.created_at.to_time)/1.day * 24
      @user = User.find_by_email(p.user_email)
    end
    #if the user doen't exist something goes wrong, may be someone trying to hack the pass reset providing another hash, so we can't let him go
    if(@user != nil && dif >= 12)
      @valid_reset = true
    end
    respond_to do |format|
      format.html 
      
    end
    
  end
  #this is the method to update the user password
  def changepass
   
    if(params[:password] == params[:password_confirmation])
      @user = User.find(params[:id])
      @user.password = params[:password]
      @user.save
      #logger.debug "EPA:FDX ESOTU AQUI!!!!!!!!!!!!!!!!!!!"
      respond_to do |format|
        format.html { redirect_to root_path, :notice=>'Dados actualizados com sucesso!!!' }
        format.js
      end
      
    else
      
      render 'passnotequal.js.erb'
    end
   
  end
  def editprofile
    @user = current_user

    p = current_user.user_pre_preference
    @rest_prefs_type1_array =[]
    rest_prefs_type1 = p.user_pre_preferences_of_restaurant_categories
    rest_prefs_type1.each { |cat|
      category = RestaurantCategory.find(cat.restaurant_category_id)
      if(category.restaurant_category_type == 1)
        cenas = {:name =>"#{category.name}", :value=>"#{cat.significance}", :id=>"#{category.id}"}
        @rest_prefs_type1_array << cenas
      end
    }
    @rest_prefs_type2_array =[]
    rest_prefs_type1 = p.user_pre_preferences_of_restaurant_categories
    rest_prefs_type1.each { |cat|
      category = RestaurantCategory.find(cat.restaurant_category_id)
      if(category.restaurant_category_type == 2)
        cenas = {:name =>"#{category.name}", :value=>"#{cat.significance}", :id=>"#{category.id}"}
        @rest_prefs_type2_array << cenas
      end
    }
   
    
  end
  def saveprofile
    
    profile = current_user.profile
    
    profile.attributes =  params[:profile]
    profile.save
    
    data = nil
    #logger.debug "UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU:" << (params[:profile][:phone_number].to_s)
    if(params[:profile][:birth_date] != nil)
      data = Date.parse(params[:profile][:birth_date].to_s)
    end
    #user.profile.home_location= "lisboa"
    profile.birth_date = data
    @user = current_user
    @user.profile = profile

    t1 = @user.user_pre_preference.user_pre_preferences_of_restaurant_categories

    @type1 = []
    @type2 = []
    t1.each { |cat|

      c = RestaurantCategory.find(cat.restaurant_category_id)
      a = {:name=>c.name, :significance=>cat.significance}
      if c.restaurant_category_type == 1

        @type1 << a
      else
        @type2 << a
      end

    }
    
   
    if(profile.save)
      render :action=>'myprofile', :notice =>'Dados do utilizador atualizados com sucesso!'
    else
      render :action=>'editprofile', :notice=>'Alguma coisa correu mal!'
    end
  end
  def myprofile
    @user = current_user
    t1 = @user.user_pre_preference.user_pre_preferences_of_restaurant_categories

    @type1 = []
    @type2 = []
    t1.each { |cat|

      c = RestaurantCategory.find(cat.restaurant_category_id)
      a = {:name=>c.name, :significance=>cat.significance}
      if c.restaurant_category_type == 1
        
        @type1 << a
      else
        @type2 << a
      end

    }
    
    
  end
  def save_rest_prefs
    
    p = current_user.user_pre_preference
    p.restaurant_categories.clear
    p.user_pre_preferences_of_restaurant_categories.clear
    ids_and_values = params[:rest_pref_ids].split(",")
    
    ids_and_values.each { |cena|
      values = cena.split(":")

      e = UserPrePreferencesOfRestaurantCategory.new
      e.restaurant_category_id = values[0]
      e.user_pre_preference_id = p.id
      e.significance   = values[1]
      e.save


    }
    #r = RestaurantCategory.find(id)
    # p.restaurant_categories << r
      
    
    if p.save
      @user = current_user
    
      redirect_to '/users/myprofile',  :notice =>'Dados do utilizador atualizados com sucesso!'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/users/_form.html.erb
<div id="formRegisto">
    <%= form_for(@user, :remote=>true) do |f| %>
      <div class="field">
        <%= f.label :name, "Primeiro Nome:", :class=>"labels" %><br />
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :last_name, "Último Nome:", :class=>"labels" %><br />
        <%= f.text_field :last_name %>
      </div>
      <div class="field">
        <%= f.label :email, "E-Mail:", :class=>"labels" %><br />
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :password, "Palavra Chave:", :class=>"labels" %><br />
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation, "Confirmação da Palavra Chave:", :class=>"labels" %><br />
        <%= f.password_field :password_confirmation %>
      </div>
      <div class="divBotao">
        <%= f.submit "Registar", :class=>"botaoRegistarCliente" %>
      </div>
    <% end %>
</div>

app/views/users/_setpass.html.erb
<div id="setPassDiv">
<p>Insira o email que usou para o registo, será enviado um email com as instruções para recuperar a sua palavra chave!</p>
<form id="setpass" accept-charset="UTF-8" action="users/sendpassemail" data-remote="true" method="get" style="display: block; " class="boxy-content">
  <div style="margin:0;padding:0;display:inline">
    <input name="utf8" type="hidden" value="✓"/></div>
  <label for="email">E-mail de registo:</label>
  <input id="email" name="email" type="text" />
  <input id="resetPassButton" name="commit" type="button" value="Submeter" onclick="submitSetPass()"/>
</form>
</div>

app/views/users/contents.html.erb
<br/>
<script type="text/javascript">
  $('.contentsOptions').corner("5px");
  $('.contentstitles').corner("5px");
</script>
<div id="conteudosUser">
  <table border="0" width="880" cellspacing="0" cellpadding="0" >
    <tr>
      <td valign="top" >
        <div id="conteudosLeft">
          <div class="contentstitles">Últimos conteúdos adicionados</div>
          bababbababa
          <br/>
          <div class="contentstitles">Últimos comentários aos meus conteúdos</div>
          
          <br/>çslakk +psal d
          <br/>çlask +k 
          vposkadpo poska dpoks ad<br/>poskadpo poska dpoks ad<br/>
          poskadpo poska dpoks ad<br/>

        </div>
      </td>
      <td valign="top">
        <div id="conteudosRight">
          <div class="contentsOptions">
            <%=  link_to "Adicionar/Editar Hotéis", "/usercontents/edithotels" %>
          </div>
          <br/>
          <div class="contentsOptions">
            <%=  link_to "Adicionar/Editar Restaurantes", "/usercontents/editrestaurants" %>
          </div>
          <br/>
          <div class="contentsOptions">
            <%=  link_to "Adicionar/Editar Pontos de Interesse", "/usercontents/editintpoints" %>
          </div>
          <br/>
          <div class="contentsOptions">
            <%=  link_to "Adicionar/Editar Eventos", "/usercontents/editevents" %>
          </div >
          <br/>
          <div class="contentsOptions">
          <%=  link_to "Adicionar/Editar Artigos", "/usercontents/editarticles" %>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/users/create.js.erb
$("[class^='boxy-']").remove();
$.jnotify("Caro utilizador o seu registo foi efectuado com sucesso!", 4000);

app/views/users/edit.erb
<h1>Editing user</h1>
<%= render 'form' %>
<%= link_to 'Voltar', home_path %>

app/views/users/editprofile.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    
    $("#profile_birth_date").datepicker( "setDate" ,  '<%=  @user.profile.birth_date %>' );
    $( "#profileAccordion" ).accordion({autoHeight: false,
      navigation: true});
    $(".userPreferencesDivs").corner("5px");

    $( "ul.droptrue" ).sortable({
      connectWith: "ul"
    });

    $( "ul.dropfalse" ).sortable({
      connectWith: "ul",
      dropOnEmpty: false
    });

    $( "#sortable1, #sortable2, #sortable3, #sortable4, #sortable5" ).disableSelection();

    <% @rest_prefs_type1_array.each_with_index{|cat, i| %>
    $( "#gastronomia<%= cat[:id] %>" ).slider({
			orientation:  "horizontal",
			range: "min",
			min: 0,
			max: 10,
			value: <%= cat[:value] %>,
                        animate: true,
			slide: function( event, ui ) {
				$( "#amount<%= cat[:id] %>" ).val( ui.value );
			}
		});

		$( "#amount<%= cat[:id] %>" ).val( $( "#gastronomia<%= cat[:id] %>" ).slider( "value" ) );
                
                
  <% } %>
    <% @rest_prefs_type2_array.each_with_index{|cat, i| %>
    $( "#gastronomia<%= cat[:id] %>" ).slider({
			orientation:  "horizontal",
			range: "min",
			min: 0,
			max: 10,
			value: <%= cat[:value] %>,
                        animate: true,
			slide: function( event, ui ) {
				$( "#amount<%= cat[:id] %>" ).val( ui.value );
			}
		});

		$( "#amount<%= cat[:id] %>" ).val( $( "#gastronomia<%= cat[:id] %>" ).slider( "value" ) );


  <% } %>
    $("[id^=amount]").attr('disabled', true);
    $("[id^=amount]").css("background-color", "#EEEEEE");

    
    

      
    $("#test").click(function(){
      //var ids = $('#sortable1').sortable('toArray');
      //if(ids == "" ){
       // ids = $('#sortable4').sortable('toArray');
      //}else  if($('#sortable4').sortable('toArray')!= ""){
        //    ids = ids + "," + $('#sortable4').sortable('toArray')
        //}
      //$('#rest_pref_ids').val(ids);
       //alert(ids);
       a = $("#this_rest_cats").val().split(',');
       a.pop();
       ids_and_values = "";
       for(i = 0; i != a.length; i++){
         ids_and_values = ids_and_values + a[i] + ":"+ $("#amount"+a[i]).val() + ",";
       }
      // alert(ids_and_values);
       $('#rest_pref_ids').val(ids_and_values);
      $('#rest_prefs_form').submit();
           
    });

  });
</script>

<div id="editProfile"><br/>
  <h3 id="userEditDataTitle">Editar Dados de Utilizador</h3>
  <div id="profileContents">
    <div id="profileAccordion">
      <h3><a href="#">Dados do perfil</a></h3>
      <div style="font-size: 16px;">

        <%= form_for :profile, @user.profile, :url => { :action => "saveprofile" }, :html => { :multipart => true } do |p| %>
          <%= p.error_messages %>
          <div class="userEditElements">
            <%= p.label :foto, "Foto:", :class=>"labelsUserData" %>
            <%=  p.file_field :photo %><br />
          </div>
          <div class="userEditElements">
            <%= p.label :genero, "Género:", :class=>"labelsUserData" %>
            <%= p.radio_button(:gender, "Masculino") %>
            <%= p.label(:masculino, "Masculino",  :class=>"radioButtonsLabels") %>
            <%= p.radio_button(:gender, "Feminino") %>
            <%= p.label(:feminino, "Feminino", :class=>"radioButtonsLabels") %><br />
          </div>
          <div class="userEditElements">
            <%= p.label :birth_date, "Data de Nascimento:", :class=>"labelsUserData" %>
            <%=  p.text_field :birth_date , :size=>10 %><br />
          </div>
          <div class="userEditElements">
            <%= p.label :phone_number, "Telefone/Telemóvel:", :class=>"labelsUserData" %>
            <%=  p.text_field :phone_number %><br />
          </div>
          <div class="userEditElements">
            <%= p.label :home_city, "Cidade:", :class=>"labelsUserData" %>
            <%=  p.text_field :home_city %><br />
          </div>
          <div class="userEditElements">
            <%= p.label :home_location, "Localidade:", :class=>"labelsUserData" %>
            <%=  p.text_field :home_location %><br />
          </div>
          <div class="userEditElements">
            <%= p.label :profession, "Profissão:", :class=>"labelsUserData" %>
            <%=  p.text_field :profession %><br />
          </div>
          <div class="userEditElements">
            <%= p.label :work_location, "Localidade do Local de Trabalho:", :class=>"labelsUserData" %>
            <%=  p.text_field :work_location %><br />
          </div>
          <%= p.submit "Modificar", :class=>"botaoRegistarCliente" , :id =>"buttonSaveProfile"%>
        <% end %>



      </div>
      <h3><a href="#">As minhas preferências</a></h3>
      <div>


        <div class="userPreferencesDivs">
          Hotéis
          <hr/>
        </div>
        <div class="userPreferencesDivs">
          Restaurantes
          <hr/>
          <p>Atribua de 1 a 10 a importância de cada gastromia para si!</p>
          <table align="center">
             <%  @rest_prefs_type1_array.each_with_index{|cat, i|  %>
            <tr>
              <td><label for="amount<%= cat[:id] %>" style="border:0; font-size: 12px;"><%= cat[:name] %>:</label>
              </td>
              <td><input type="text" id="amount<%= cat[:id] %>"size="5" style="border:0; color:#f6931f; font-weight:bold; font-size: 12px;" /></td>
              <td> <div id="gastronomia<%= cat[:id] %>" style="width:260px; margin:15px;"></div></td>
            </tr>



              <% } %>
            
          </table>
          
           <p>Atribua de 1 a 10 a importância de cada gama de preço para si!</p>
          <table align="center">
             <%  @rest_prefs_type2_array.each_with_index{|cat, i|  %>
            <tr>
              <td><label for="amount<%= cat[:id] %>" style="border:0; font-size: 12px;"><%= cat[:name] %>:</label>
              </td>
              <td><input type="text" id="amount<%= cat[:id] %>"size="5" style="border:0; color:#f6931f; font-weight:bold; font-size: 12px;" /></td>
              <td> <div id="gastronomia<%= cat[:id] %>" style="width:260px; margin:15px;"></div></td>
            </tr>



              <% } %>

          </table>
           <%
            a = @rest_prefs_type1_array + @rest_prefs_type2_array
            string_ids = ""
            a.each{|cat|
              string_ids = string_ids + cat[:id] +","
            }

            %>
           <input type="hidden" id="this_rest_cats"value="<%= string_ids %>"/>
            <%= form_tag '/users/save_rest_prefs', :id => 'rest_prefs_form' , :remote=>false   do %>
              <%= hidden_field_tag "rest_pref_ids", ""%>
            <% end %>


            <br clear="both" />
            <%= submit_tag("Modificar", {:id => "test", :class=>"botaoRegistarCliente"}) %>



           

             
            
          </div>
                 
        
          <div class="userPreferencesDivs">

            Pontos de interesse
            <hr/>
          </div>
          <div class="userPreferencesDivs">
            Eventos
            <hr/>
          </div>



        </div>
        <h3><a href="#">Dados de conta</a></h3>
        <div>


          <%= form_for :user, @user, :url => { :action => "updateaccount" } do |u| %>
            <%= u.error_messages %>
            <div class="userEditElements">
              <%= u.label :name, "Primeiro Nome:", :class=>"labelsUserData" %>
              <%=  u.text_field :name %><br />
            </div>
            <div class="userEditElements">
              <%= u.label :last_name, "Ultimo Nome:", :class=>"labelsUserData" %>
              <%=  u.text_field :last_name %><br />
            </div>
            <div class="userEditElements">
              <%= u.label :email, "E-mail:", :class=>"labelsUserData" %>
              <%=  u.text_field :email %><br />
            </div>
            <div class="userEditElements">
              <%= u.label :password, "Palavra Chave:", :class=>"labelsUserData" %>
              <%= u.password_field :password,  :value=>"" %><br />
            </div>
            <div class="userEditElements">
              <%= u.label :password_confirmation, "Confirmação da Palavra Chave:", :class=>"labelsUserData" %>
              <%= u.password_field :password_confirmation %><br />
            </div>
            <%= u.submit "Modificar", :class=>"botaoRegistarCliente", :id=>"buttonSaveAccount" %>
          <% end %>

        </div>

      </div>

    </div>
    <br/>
  </div>

app/views/users/myprofile.erb
<div id="myProfile" ><br/>
  <h3 class="titles">A Minha Conta</h3>
  <div id="backButton"><%= link_to "Voltar", "/" %></div>
  <div id="setDadaButton"><%= link_to "Editar Dados", "/users/editprofile" %></div>
  <div id="top"style=""></div>
  <div id="middle">
    <br/>

    <div id="photoDiv">
      <% if (@user.profile.photo_file_name != nil) %>
        <%= image_tag @user.profile.photo.url(:thumb) , :id=>"defaul_image"%>
      <% else %>
        <%= image_tag "default_photo.png", :id=>"defaul_image" %>
      <% end %>
    </div>
    <div id="myProfileData">
      <h4>Dados da conta</h4>
      <div class="elements"><div class="myprofileLabels">Primeiro Nome: </div><%= @user.name %></div>
      <div class="elements"><div class="myprofileLabels">Último Nome: </div><%= @user.last_name %></div>
      <div class="elements"><div class="myprofileLabels">E-mail: </div><%= @user.email %></div>
      <hr />
      <h4>Dados do perfil</h4>
      <div class="elements"><div class="myprofileLabels">Género: </div><%= (@user.profile.gender==nil || @user.profile.gender== "")?"Por preencher!": @user.profile.gender %></div>
      <div class="elements"><div class="myprofileLabels">Data de Nascimento: </div><%= (@user.profile.birth_date==nil || @user.profile.birth_date== "")?"Por preencher!": @user.profile.birth_date %></div>
      <div class="elements"><div class="myprofileLabels">Telefone/Telemóvel: </div><%=   (@user.profile.phone_number==nil || @user.profile.phone_number== "")?"Por preencher!": @user.profile.phone_number %></div>
      <div class="elements"><div class="myprofileLabels">Localidade: </div><%= (@user.profile.home_location==nil || @user.profile.home_location== "")?"Por preencher!": @user.profile.home_location %></div>
      <div class="elements"><div class="myprofileLabels">Cidade: </div><%= (@user.profile.home_city==nil || @user.profile.home_city== "")?"Por preencher!": @user.profile.home_city %></div>
      <div class="elements"><div class="myprofileLabels">Profissão: </div><%= (@user.profile.profession==nil || @user.profile.profession== "")?"Por preencher!": @user.profile.profession %></div>
      <div class="elements"><div class="myprofileLabels">Localidade do Local de Trabalho: </div><%= (@user.profile.work_location==nil || @user.profile.work_location== "")?"Por preencher!": @user.profile.work_location %></div>
      <hr/>
      <h4>As minhas preferências</h4>
      <br/>
      <div class="my_prefs_titles">Preferências para hotéis</div>
      <hr/>
      <div class="my_prefs_titles">Preferências para restaurantes</div>
      <hr/>
      <table id="xpto"align="center" cellspacing="10" border="0">
        <thead>
          <tr>
            <td colspan="2">
              <span class="titulos_rest_cat_user_data">Tipos de Gastronomia</span>
            </td>
            
            <td style="width: 20px;">
               &nbsp;
            </td>
            <td colspan="2">
              <span class="titulos_rest_cat_user_data">Gamas de Preço</span>
            </td>
            
          </tr>
        </thead>
        <tr>
          <td><b>Nome</b></td><td><b>Significância</b></td><td></td><td><b>Nome</b></td><td><b>Significância</b></td>
        </tr>
        <tr>
          <td><%  @type1.each{ |cat| %>

            <label><%= cat[:name]  %> </label><br/><br/>
            <%  } %></td><td>
            <%  @type1.each{ |cat| %>

            <label><%= cat[:significance]  %> </label><br/><br/>
            <%  } %>
          </td><td></td><td>
            <%  @type2.each{ |cat| %>

            <label><%= cat[:name]  %> </label><br/><br/>
            <%  } %>
          </td><td>
            <%  @type2.each{ |cat| %>

            <label><%= cat[:significance]  %> </label><br/><br/>
            <%  } %>
          </td>
        </tr>
      </table>
      
      <div class="my_prefs_titles">Preferências para pontos de interesse</div>
      <hr/>
      <div class="my_prefs_titles">Preferências para eventos</div>
      <hr/>

    </div>

    <br/>
  </div>


  <div id="bottom"></div>
  <br/>
</div>

app/views/users/new.html.erb
<%= render :partial=>'/users/form' %>
<%= link_to 'Voltar', root_path %>

app/views/users/new.js.erb
$("[class^='boxy-']").remove();
new Boxy('<%= escape_javascript render(:partial => 'form') %> ', {title: "Registo de Cliente", modal:true,closeText:"<img src='/images/x.png' />"}, function() { alert("Confirmed!"); });

app/views/users/nonexist.js.erb
$("[class^='boxy-']").remove();
$('#wait').hide();
$('#waitimg').hide();

new Boxy('<p class="error">O e-mail que introduziu não existe na base de dados!</p><%= escape_javascript render(:partial => 'setpass') %> ', {title: "Recuperação de palavra chave", modal:true,closeText:"<img src='/images/x.png' />"}, function() { alert("Confirmed!"); });

app/views/users/resetpass.html.erb
<div id="formResetPass">
<%= content_tag(:p, alert, :class => 'alert') if alert.present? %>
<% if (notice.present?) %><script type="text/javascript"> $.jnotify("<%= notice %>", 5000);</script> <% end %>
<% if(@valid_reset) %>
<%=    render :partial =>'formPassReset' %>


<% else %>
<div id="resetPassNonUser"><script type="text/javascript">jAlert('Caro utilizador, o seu pedido de mudança de password expirou, para o voltar a fazer deve de efectuar um novo pedido!','Atenção', function(){window.location.replace("http://localhost:3000");});  </script> </div>
<% end %>

</div>

app/views/users/saveprofile.html.erb
<% if (@user.profile.photo_file_name != nil) %>
  <%= image_tag @user.profile.photo.url(:thumb) %>
<% else %>
<%= image_tag "default_photo.png", :id=>"defaul_image" %>
<% end %>

app/views/users/sendpassemail.js.erb
$("[class^='boxy-']").remove();
 $('#login a').removeClass('active');
        $('#loginForm').animate({'height':'hide'}, {duration:'fast'});
         $('#ui_block_div').hide();
         $('#wait').hide();
         $(' #waitimg').hide();

jAlert('Foi-lhe enviado um email para proceder à recuperação da palavra chave!','E-mail enviado');

app/views/users/setpass.js.erb
$("[class^='boxy-']").remove();
new Boxy('<%= escape_javascript render(:partial => 'setpass') %> ', {title: "Recuperação de palavra chave", modal:true,closeText:"<img src='/images/x.png' />"}, function() { alert("Confirmed!"); });